version: '3.8'

services:
  server1:
    build: .
    command: python servidor.py 5001
    volumes:
      - ./data1:/app/data 
    ports:
      - "5001:5001"

  server2:
    build: .
    command: python servidor.py 5002
    volumes:
      - ./data2:/app/data 
    ports:
      - "5002:5002"

  client1:
    build: .
    command: python cliente.py server1 5001
    depends_on:
      - server1

  client2:
    build: .
    command: python cliente.py server2 5002
    depends_on:
      - server2